config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "notes#index"
  resources :notes do
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
      get 'detail_search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    get :favorites, on: :collection
  end
  # get'/show/:id' => 'notes#show'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :text, presence: true
  validates :user, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :user, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title, :status, :subject, :text ,presence: true
  validates :images, presence: true

  def self.search(search)
    return Note.all unless search
    Note.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :birthday ,presence: true
  has_many :notes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    if comment.save
      flash[:notice] = "コメントを投稿しました。"
    else
      flash[:alert] = "コメントを送信できませんでした"
    end
    redirect_to note_path(comment.note.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, note_id: params[:note_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_note, only: [:create, :destroy]

  def create
    @favorite = Favorite.create(user_id: current_user.id, note_id: @notes.id)
    @favorite.save
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, note_id: @notes.id)
    @favorite.destroy
  end

  private
  def set_note
    @notes = Note.find(params[:note_id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :detail_search

  def index
    @notes = Note.all.with_attached_images.order(created_at: :desc)
    @all_ranks = Note.find(Favorite.group(:note_id).order('count(note_id) desc').limit(5).pluck(:note_id))
    @random = Note.order("RAND()").limit(5)
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.valid?
      @note.save
      flash[:notice] = "投稿に成功しました。"
      redirect_to root_path
    else
      flash[:alert] = "必須項目が抜けています。"
      render :new
    end
  end

  def show
    @notes = Note.with_attached_images.find(params[:id])
    @comment = Comment.new
    @comments = @notes.comments.includes(:user).reverse
  end

  def destroy
    @notes = Note.find(params[:id])
    @notes.destroy
    flash[:notice] = "削除が完了しました。"
    redirect_to root_path
  end

  def edit
    @notes = Note.find(params[:id])
    if @notes.user == current_user
      render :edit
    else
      flash[:alert] = '予期せぬ操作がありました。'
      redirect_to root_path
    end
  end

  def update
    @notes = Note.find(params[:id])
    if @notes.user == current_user
      if @notes.update(note_params)
        flash[:notice] = "ノートの編集に成功しました。"
      else
        flash[:alert] = "ノートの編集に失敗しました。"
      end
    end
    redirect_to root_path
  end

  def search
    @notes = Note.with_attached_images.search(params[:keyword])
  end

  private

  def note_params
    params.require(:note).permit(:title, :status, :subject, :text, images: []).merge(user_id: current_user.id)
  end

  def detail_search
    @search = Note.with_attached_images.ransack(params[:q])
    @notes = @search.result(distinct: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @notes = Note.with_attached_images.where(user_id: current_user.id)
    @favorites = Favorite.includes(:note).where(user_id: current_user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        flash[:notice] = 'ユーザー情報を編集しました。'
      else
        flash[:alert] = 'ユーザー情報の編集に失敗しました。'
      end
    end
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "退会処理が完了しました。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.haml
.favorite
  - if !Favorite.exists?(user: current_user, note_id: @notes.id)
    = link_to note_favorites_path(@notes), method: :post, remote: true, class: "favorite-btn" do
      %i.fas.fa-book-open
    %span このノートのお気に入り数:
    = @notes.favorites.length
  - else
    = link_to note_favorites_path(@notes), method: :delete, remote: true, class: "favorite-btn" do
      %i.fas.fa-book-open
    %span このノートのお気に入り数:
    = @notes.favorites.length

app/views/favorites/create.js.erb
$('#favorite_<%= @notes.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { note: @notes }) %>");

app/views/favorites/destroy.js.erb
$('#favorite_<%= @notes.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { note: @notes }) %>");

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs pretext: " ",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Nota
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/notes/_appbanner.html.haml
.appbanner
  .inner
    %h2.inner__title だれでもかんたん、学習で人生を変えるアプリ
    %p.inner__text 今すぐ無料ダウンロード！
    .inner__icon
      =link_to "#" do
        =image_tag "app_store.png", class: "aBtn", height: "54px", width: "190px"
      =link_to "#" do
        =image_tag "google_play.png", class: "gBtn", height: "54px", width: "190px"

app/views/notes/_appinfo.html.haml
.appinfo
  .info_text
    %h.info_first Notaは小学校の内容からTOEICまで幅広く学習できます。
    %br
    %h.info_second 誰でも簡単に投稿・閲覧が可能！
    %br
    %h.info_third 投稿したノートの「いいね!」が多ければランキングトップに!

app/views/notes/_footer.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content_head Notaについて
      %ul
        %li
          =link_to  "会社概要（運営会社）"
        %li
          =link_to  "プライバシーポリシー"
        %li
          =link_to  "Nota利用規約"
    %li.content
      %h2.content_head Notaを見る
      %ul
        %li
          =link_to  "学年一覧"
        %li
          =link_to  "科目一覧"
    %li.content
      %h2.content_head ヘルプ＆ガイド
      %ul
        %li
          =link_to  "Notaガイド"
        %li
          =link_to  "お問い合わせ"
        %li
          =link_to  "お知らせ"
        - if user_signed_in?
          - if current_user == @user || current_user.admin?
            %li
              =link_to  "管理者", admin_root_path
  .footer_logo
    =link_to root_path do
      %p © Nota

app/views/notes/_header.html.haml
.header
  .header_main
    .header_main__left
      = link_to root_path do
        %p.title Nota
    .header_main__center
      = form_with url: search_notes_path, local: true, method: :get, class: "search_form" do |form|
        = form.text_field :keyword, placeholder: "キーワードから探す", class: "search_form_input"
        = form.submit "検索", class: "search_form_btn"
    .header_main__right
      = link_to '詳細検索', search_notes_path, class: "search_detail"
  .header_sub
    - if user_signed_in?
      .header_sub__login
        = link_to 'ログアウト', destroy_user_session_path, class: "logout_btn"
      .header_sub__register
        = link_to '新規投稿', new_note_path, class: "post_btn"
      .header_sub__register
        = link_to "マイページ", user_path(current_user.id), class: "post_btn"
    - else
      .header_sub__login
        = link_to 'ログイン', new_user_session_path, class: "login_btn"
      .header_sub__register
        = link_to '新規登録', new_user_registration_path, class: "register_login"

app/views/notes/_main.html.haml
.main
  .main_center
    %h1.main_center-title ＜ 最新ノート ＞
    .main-center_images
      - @notes.each do |note|
        .main-center_images_image
          - if user_signed_in?
            = link_to note_path(note) do
              = image_tag note.images[0], width:"184",height:"150"
              %br
              .main-center_images_title
                = note.title
          - else
            = link_to new_user_registration_path do
              = image_tag note.images[0], width:"184",height:"150"
              %br
              .main-center_images_title
                = note.title
    %br
    %h1.main_center-title＜ピックアップノート＞
    .main-center_images
      - @random.each do |note|
        .main-center_images_image
          - if user_signed_in?
            = link_to note_path(note) do
              = image_tag note.images[0], width:"184",height:"150"
              %br
              .main-center_images_title
                = note.title
          - else
            = link_to new_user_registration_path do
              = image_tag note.images[0], width:"184",height:"150"
              %br
              .main-center_images_title
                = note.title

    %br
    %h1.main_center-title＜お気に入りランキング＞
    .main-center_images
      - @all_ranks.each.with_index(1) do |note, i|
        .main-center_images_image
          %br
          .text
            第
            = i
            位
          - if user_signed_in?
            = link_to note_path(note) do
              = image_tag note.images[0], width:"184",height:"150"
            %br
            .main-center_images_title
              = note.title
          - else
            = link_to new_user_registration_path do
              = image_tag note.images[0], width:"184",height:"150"
              %br
              .main-center_images_title
                = note.title

app/views/notes/detail_search.html.haml
= render "notes/header"
.main
  .main-search
    = search_form_for @search, url: detail_search_notes_path do |f|
      .field
        = f.label :対象, class: "main-search_info"
        %br/
        = f.select :status_eq, ['小学生', '中学生', '高校生', '大学生', '社会人'], { include_blank: '選択してください'}, { class: 'main-search_form' , required: true }
      .field
        = f.label :科目, class: "main-search_info"
        %br/
        = f.select :subject_eq, ['英語', '数学', '国語', '理科', '社会'], { include_blank: '選択してください'}, { class: 'main-search_form' , required: true }
      .field
        = f.submit "検索", class: "search_form_btn"

  .main-detail_search_images
    - @notes.each do |note|
      .main-detail_search_images_image
        - if user_signed_in?
          = link_to note_path(note) do
            = image_tag note.images[0], width:"184",height:"150"
            %br
            .main-detail_search_images_title
              = note.title
        - else
          = link_to new_user_registration_path do
            = image_tag note.images[0], width:"184",height:"150"
            %br
            .main-detail_search_images_title
              = note.title
= render "notes/appbanner"
= render "notes/footer"

app/views/notes/edit.html.haml
= render "notes/header"
- breadcrumb :edit_note
= breadcrumbs separator: " &rsaquo; "
.main_note
  .new_note
    %h.post_info ノート編集
    = form_with(model: @notes, local: true)do |f|
      .field
        = f.label :ノートタイトル, class: "new_note_info"
        %br/
        = f.text_field :title, autofocus: true, class: "new_note_form", placeholder: "例）高2英文法"
      .field
        = f.label :対象, class: "new_note_info"
        %br/
        = f.select :status, ['小学生', '中学生', '高校生', '大学生', '社会人'], { include_blank: '選択してください'}, { class: 'note_status_form' , required: true }
      .field
        = f.label :科目, class: "new_note_info"
        %br/
        = f.select :subject, ['英語', '数学', '国語', '理科', '社会'], { include_blank: '選択してください'}, { class: 'note_subject_form' , required: true }
      .field
        = f.label :ノート説明, class: "new_note_info"
        %br/
        = f.text_area :text, autofocus: true, class: "new_note_text", placeholder: "例）高校2年で関習った係代名詞をまとめたノートです。"
      .actions
        = f.submit "編集する", class: "new_note_btn"
= render "notes/appbanner"
= render "notes/footer"

app/views/notes/index.html.haml
.wrapper
  = render "header"
  = render "appinfo"
  = render "main"
  = render "appbanner"
  = render "footer"

app/views/notes/new.html.haml
= render "notes/header"
- breadcrumb :new_note
= breadcrumbs separator: " &rsaquo; "
.main_note
  .new_note
    %h.post_info ノート投稿
    = form_with(model: @note, local: true)do |f|
      .field
        = f.label :ノートタイトル, class: "new_note_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        = f.text_field :title, autofocus: true, class: "new_note_form", placeholder: "例）高2英文法", id: "title"
      .field
        = f.label :ノート画像（最大4枚まで投稿可能）, class: "new_note_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        #image_box
          .note-num-0#image-box__container
            = f.fields_for :images do |i|
              .js-file_group{"data-index" => "#{i.index}"}
                = f.file_field :images, multiple: true, class: "js-file", type: 'file', value:"", style: "display:none", id:"img-file"
              %br/
              %span.js-remove
        %label{for: "img-file"}
          %i.fas.fa-camera
      .field
        = f.label :対象, class: "new_note_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        = f.select :status, ['小学生', '中学生', '高校生', '大学生', '社会人'], { include_blank: '選択してください'}, { class: 'note_status_form' , required: true }
      .field
        = f.label :科目, class: "new_note_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        = f.select :subject, ['英語', '数学', '国語', '理科', '社会'], { include_blank: '選択してください'}, { class: 'note_subject_form' , required: true }
      .field
        = f.label :ノート説明, class: "new_note_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        = f.text_area :text, autofocus: true, class: "new_note_text", placeholder: "例）高校2年で関習った係代名詞をまとめたノートです。", id: "text"
      .actions
        = f.submit "投稿する", class: "new_note_btn"
= render "notes/appbanner"
= render "notes/footer"

app/views/notes/search.html.haml
= render "notes/header"
- breadcrumb :search_note
= breadcrumbs separator: " &rsaquo; "
.main
  .main-search
    = search_form_for @search, url: detail_search_notes_path do |f|
      .field
        = f.label :対象, class: "new_note_info"
        %br/
        = f.select :status_eq, ['小学生', '中学生', '高校生', '大学生', '社会人'], { include_blank: '選択してください'}, { class: 'note_status_form' , required: true }
      .field
        = f.label :科目, class: "new_note_info"
        %br/
        = f.select :subject_eq, ['英語', '数学', '国語', '理科', '社会'], { include_blank: '選択してください'}, { class: 'note_subject_form' , required: true }
      = f.submit "検索", class: "search_form_btn"

  .main-search_images
    - @notes.each do |note|
      .main-search_images_image
        - if user_signed_in?
          = link_to note_path(note) do
            = image_tag note.images[0], width:"184",height:"150"
            %br
            .main-search_images_title
              = note.title
        - else
          = link_to new_user_registration_path do
            = image_tag note.images[0], width:"184",height:"150"
            %br
            .main-center_images_title
              = note.title
= render "notes/appbanner"
= render "notes/footer"

app/views/notes/show.html.haml
= render "notes/header"
- breadcrumb :note
= breadcrumbs separator: " &rsaquo; "
.main
  = render "users/left"

  .main_right
    .main_right_contents
      .main_right_contents_title
        = @notes.title
        %h の詳細
      .main_right_contents_content
        .main_right_contents_name
          %h 投稿者：
          = @notes.user.nickname
        .main_right_contents_status
          %h 対象：
          = @notes.status
        .main_right_contents_subject
          %h 科目：
          = @notes.subject
      .main_right_contents_images
        - @notes.images.each do |image ,i|
          .main_right_contents_images_image
            = image_tag image, width:"400",height:"350"
      %h ＜ ノート説明 ＞
      %i.fas.fa-arrow-circle-down
      .main_right_contents_text
        =@notes.text
      .main_right_contents_btn
        - if @notes.user_id == current_user.id
          = link_to '削除', @notes, method: :delete, class: "delete_btn", data: { confirm: '削除しますか?' }
          %br
          = link_to '編集', "/notes/#{@notes.id}/edit", method: :get, class: "edit_btn"
    .main_right_functions
      .main_right_favotite
        #favorite{ id: @notes.id }
          = render "favorites/favorite"
      .main_right_comment
        = form_with(model:[@notes, @comment], local: true) do |f|
          = f.text_area :text, placeholder:"コメントを入力してください", rows:"2", class:"comment_form"
          %br
          = f.submit "投稿する", class:"comment_btn"
    %h ＜コメント一覧＞
    %i.fas.fa-arrow-circle-down
    .main_right_comments
      - @comments.each do |c|
        %p
          %strong
            = c.user.nickname
            ：
          = c.text
          %br
          コメント時間
          = c.created_at.strftime("%Y-%m-%d %H:%M")
= render "notes/appbanner"
= render "notes/footer"

app/views/users/_left.html.haml
.main_left
  %dl#main_left_acmenu
    %dt・メイン
    %dd
      = link_to 'トップページ', root_path, class: 'leftmenu'
      %br
      = link_to "マイページ", user_path(current_user.id), class: "leftmenu"
      %br
      = link_to '新規投稿', new_note_path, class: "leftmenu"
      %br
      = link_to 'お問い合わせ', '＃', class: 'leftmenu'
    %dt ・各種設定
    %dd
      = link_to 'ユーザー情報の編集', edit_user_path, method: :get, class: 'leftmenu'
      %br
      = link_to 'ログアウト', destroy_user_session_path, class: "leftmenu"
      %br
      = link_to '退会する', user_path(current_user.id), method: :delete, class: "leftmenu", data: { confirm: '退会しますか?' }

app/views/users/edit.html.haml
= render "notes/header"
- breadcrumb :edit_user
= breadcrumbs separator: " &rsaquo; "
.main_register
  .new_register
    %h2.new_register_title ユーザー情報変更
    = form_with(model: current_user, local: true) do |f|
      .field
        = f.label :ニックネーム, class: "new_register_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        = f.text_field :nickname, autofocus: true, class: "new_register_form", placeholder: "例）Nota太郎"
      .field
        = f.label :メールアドレス, class: "new_register_info"
        %span.sign-up-content__main__form__group__require 必須
        %br/
        = f.email_field :email, autofocus: true, autocomplete: "email", class: "new_register_form", placeholder: "例）nota@nota.com"
      .actions
        = f.submit "変更する", class: "new_register_btn"

= render "notes/appbanner"
= render "notes/footer"

app/views/users/show.html.haml
= render "notes/header"
- breadcrumb :mypage
= breadcrumbs separator: " &rsaquo; "
.main
  = render "users/left"

  .main_right
    .main_right_contents
      %h.main_right_user= current_user.nickname
      さんのノート一覧
      .main_right_images
        - @notes.each do |note|
          .main_right_images_image
            = link_to note_path(note) do
              = image_tag note.images[0], width:"184",height:"150"
              %br
              .main_right_images_title
                = note.title
    .main_right_contents
      %h.main_right_user= current_user.nickname
      さんのお気に入りノート一覧
      %i.fas.fa-arrow-circle-down
      .main_right_content
        .main_right_favorites
          - if @favorites.present?
            - @favorites.each do |f|
              .main_right_images_image
                = link_to note_path(f.note) do
                  = image_tag f.note.images[0], width:"184",height:"150"
                  %br
                  .main_right_images_title
                    = f.note.title
          - else
            %h1 お気に入りはまだ登録されていないです。

= render "notes/appbanner"
= render "notes/footer"